"""Configuration management for the Do-Good GitHub Agent."""

import os
import subprocess
from pathlib import Path
from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).parent.parent
load_dotenv(PROJECT_ROOT / ".env")


def _get_gh_token() -> str:
    """Get GitHub token from env or gh CLI."""
    token = os.getenv("GITHUB_TOKEN", "")
    if token:
        return token
    try:
        result = subprocess.run(
            ["gh", "auth", "token"], capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return ""


# --- GitHub ---
GITHUB_TOKEN = _get_gh_token()
GITHUB_USERNAME = os.getenv("GITHUB_USERNAME", "danielalanbates")
GITHUB_GRAPHQL_URL = "https://api.github.com/graphql"

# --- Paths ---
DATA_DIR = PROJECT_ROOT / "data"
DB_PATH = DATA_DIR / "github_helper.db"
WORK_DIR = Path(os.getenv("WORK_DIR", "/tmp/dogood-workdir"))
SEED_DATA_PATH = PROJECT_ROOT / "awesome-for-beginners" / "data.json"

# --- Rate Limiting ---
SEARCH_DELAY_SECONDS = 2.5  # ~24 searches/min (safe under 30/min limit)

# --- Scoring Weights ---
WEIGHT_POPULARITY = 0.20
WEIGHT_SOCIAL_IMPACT = 0.30
WEIGHT_NEED = 0.25
WEIGHT_KINDNESS = 0.25

# --- Social Impact Topics ---
SOCIAL_TOPICS = {
    "nonprofit", "charity", "social-impact", "tech-for-good",
    "accessibility", "a11y", "education", "edtech", "health",
    "healthcare", "climate", "sustainability", "environment",
    "open-data", "civic-tech", "humanitarian", "disaster-relief",
    "food-security", "clean-water", "poverty", "human-rights",
    "mental-health", "assistive-technology",
}

# --- Bounty labels (top priority, always use opus) ---
BOUNTY_LABELS = {
    "bounty", "reward", "paid", "cash", "💰", "💵",
    "has bounty", "has-bounty", "bounty-posted",
}

# --- Labels reserved for human beginners (we skip these) ---
BEGINNER_LABELS = {
    "good first issue", "good-first-issue", "beginner",
    "easy", "first-timers-only", "starter", "low-hanging-fruit",
    "up-for-grabs",
}

# --- Ethics Filter ---
# Repos/topics we refuse to contribute to. We only help build things that
# are wholesome and align with Christian values.
BLOCKED_TOPICS = {
    "nsfw", "adult", "porn", "pornography", "sex", "erotic", "hentai",
    "xxx", "nudity", "onlyfans", "cam", "escort", "fetish", "strip",
    "gambling", "casino", "betting", "slot-machine",
    "drugs", "drug-market", "darknet-market",
    "weapon", "exploit-kit", "malware", "ransomware", "spyware",
    "occult", "satanism", "witchcraft",
}
BLOCKED_DESCRIPTION_KEYWORDS = {
    "pornograph", "adult content", "nsfw", "erotic", "sex toy",
    "gambling platform", "casino", "betting platform",
    "drug market", "darknet", "exploit kit", "malware",
}

# --- Anti-AI Policy Detection ---
# Keywords in CONTRIBUTING.md / README.md that indicate AI contributions are banned.
ANTI_AI_KEYWORDS = {
    "no ai", "no llm", "ai-generated", "ban ai", "no bots",
    "ai contributions not accepted", "ai-free", "no machine",
    "ai-generated contributions", "do not use ai", "don't use ai",
    "generated by ai", "written by ai", "no copilot",
    "no chatgpt", "no claude", "llm-generated",
}

# --- Supported Languages ---
# We only fix bugs in repos whose primary language is one of these.
SUPPORTED_LANGUAGES = {
    "Python", "JavaScript", "TypeScript", "Shell", "Bash",
    "YAML", "SQL", "HTML", "CSS", "Nunjucks", "EJS", "Astro",
    "Vue", "Svelte", "SCSS", "Less", "Markdown", "Lua",
}

# File extensions we can work with (mapped from SUPPORTED_LANGUAGES)
SUPPORTED_EXTENSIONS = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs",
    ".sh", ".bash", ".zsh",
    ".yaml", ".yml", ".sql", ".lua",
    ".html", ".htm", ".css", ".scss", ".less",
    ".vue", ".svelte", ".astro", ".ejs", ".njk",
    ".md", ".mdx", ".json", ".toml",
}

# File extensions that signal the bug is NOT in our wheelhouse
UNSUPPORTED_EXTENSIONS = {
    ".rs", ".go", ".java", ".kt", ".scala", ".clj",
    ".c", ".cpp", ".cc", ".cxx", ".h", ".hpp",
    ".cs", ".rb", ".php", ".swift", ".m", ".mm",
    ".r", ".R", ".jl", ".hs", ".erl", ".ex", ".exs",
    ".dart", ".pl", ".pm",
}

# --- CLA/DCO Detection ---
# Keywords that indicate a repo requires a CLA (Contributor License Agreement)
# or DCO (Developer Certificate of Origin) sign-off. We skip these repos
# unless we've already signed their CLA.
CLA_KEYWORDS = {
    "contributor license agreement", "cla", "contributor agreement",
    "sign the cla", "signed cla", "cla-assistant", "cla assistant",
    "license agreement", "individual contributor license",
    "corporate contributor license",
}
DCO_KEYWORDS = {
    "developer certificate of origin", "dco", "signed-off-by",
    "sign-off", "signoff",
}
# Workflow files that indicate CLA/DCO enforcement
CLA_WORKFLOW_FILES = [
    ".github/workflows/cla.yml",
    ".github/workflows/cla.yaml",
    ".github/workflows/dco.yml",
    ".github/workflows/dco.yaml",
]

# Organizations known to require CLAs — skip ALL repos in these orgs
# unless we've explicitly signed their CLA
CLA_ORGS = {
    "google", "googleapis", "angular", "tensorflow",  # Google CLA
    "microsoft", "azure", "dotnet",                    # Microsoft CLA
    "apache",                                          # Apache ICLA
    "eclipse",                                         # Eclipse ECA
    "salesforce",                                      # Salesforce CLA
    "SAP",                                             # SAP CLA
    "Shopify",                                         # Shopify CLA
    "hashicorp",                                       # HashiCorp CLA
    "chef",                                            # Chef CLA
    "adobe",                                           # Adobe CLA
    "dequelabs",                                       # Deque CLA (axe-core)
    "brave",                                           # Brave CLA
    "home-assistant",                                  # Home Assistant CLA
    "processing",                                      # Processing Foundation CLA
    "mlflow",                                          # MLflow CLA (Linux Foundation)
}

# Organizations where we HAVE signed the CLA
SIGNED_CLA_ORGS = {
    "facebook", "meta", "pytorch",  # Meta CLA signed (pytorch uses Meta CLA)
}

# --- Multi-Agent Factory ---
MAX_CONCURRENT_AGENTS = int(os.getenv("MAX_CONCURRENT_AGENTS", "1"))  # Tier 1 = 50 RPM, only 1 agent at a time
AGENT_CLAIM_TTL_MINUTES = 120
MIN_STARS_DEFAULT = 1000  # lowered from 10000
FEEDBACK_POLL_INTERVAL_SECONDS = 300
HOSTILE_SENTIMENT_THRESHOLD = 0.7
MAX_OPUS_PER_ISSUE = 10  # max opus attempts per individual issue before capping at sonnet

# --- Model Tiers ---
# Start with Sonnet (no haiku). Escalate to Opus only for reviews/complaints.
MODEL_TIERS = [
    {
        "tier": 1,
        "model": "claude-sonnet-4-6",
        "effort": "medium",
        "label": "sonnet-medium",
        "description": "All issues, single-file and multi-file bugs",
    },
    {
        "tier": 2,
        "model": "claude-sonnet-4-6",
        "effort": "high",
        "label": "sonnet-high",
        "description": "Complex multi-file bugs, refactoring",
    },
    {
        "tier": 3,
        "model": "claude-opus-4-6",
        "effort": "high",
        "label": "opus-high",
        "description": "Reviewer complaints, quality re-fixes, architectural",
    },
]

# --- Log file ---
LOG_FILE = PROJECT_ROOT / "Claude Agent - Do-Good GitHub Helper.md"
